version: "3.3"
services:
  web:
    build: 
      context: ..
      dockerfile: ./odoo-dev-env/Dockerfile
    ports:
      - "8069:8069"
    depends_on:
      - db
    volumes:
      - ../odoo:/home/odoo/app
      - odoo-data:/var/lib/odoo
    networks:
      - odoo

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - odoo
    restart: unless-stopped
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - odoo
    restart: unless-stopped
    
networks:
  odoo:
    driver: bridge
    
volumes:
  odoo-data: {}
  odoo-db-data: {}
  pgadmin-data: {}
